(function(){'use strict';
const API='/api/project-hub';let _t=null,_p=null,_ch=null;
function T(){if(_t)return _t;try{const s=JSON.parse(sessionStorage.getItem('qsp_session')||'{}');if(s.access_token){_t=s.access_token}}catch(e){}return _t}
function P(){if(_p)return _p;const u=new URLSearchParams(location.search);_p=u.get('id')||u.get('project_id');return _p}
async function A(r,m='GET',b=null,x={}){const t=T();if(!t)throw new Error('Not logged in');const p=new URLSearchParams({resource:r,...x});const o={method:m,headers:{'Authorization':'Bearer '+t,'Content-Type':'application/json'}};if(b)o.body=JSON.stringify(b);const res=await fetch(API+'?'+p,o);const d=await res.json();if(!res.ok)throw new Error(d.error||'HTTP '+res.status);return d}
const F=n=>Number(n||0).toLocaleString('en-QA',{maximumFractionDigits:0});

async function initBOQTab(c){c.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;flex-wrap:wrap;gap:8px"><h3 style="color:#C8922A;margin:0">BOQ</h3><div><button onclick="QS_Phase9._add()" style="padding:8px 12px;background:#C8922A;color:#fff;border:none;border-radius:6px;cursor:pointer;font-weight:700;font-size:12px">+ بند</button> <button onclick="QS_Phase9._csv()" style="padding:8px 12px;background:#1A5276;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px">CSV</button></div></div><div id="boq-s" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:6px;margin-bottom:10px"></div><div id="boq-t" style="overflow-x:auto"></div>';await _lb()}
async function _lb(){try{const r=await A('boq','GET',null,{project_id:P()});const s=r.summary||{};document.getElementById('boq-s').innerHTML='<div style="background:#111;border:1px solid #222;border-radius:8px;padding:8px;text-align:center"><div style="font-size:20px;font-weight:700;color:#C8922A">'+s.total_items+'</div><div style="font-size:10px;color:#888">بنود</div></div><div style="background:#111;border:1px solid #222;border-radius:8px;padding:8px;text-align:center"><div style="font-size:14px;font-weight:700;color:#7FB3D3">'+F(s.total_contracted)+' QR</div><div style="font-size:10px;color:#888">عقد</div></div><div style="background:#111;border:1px solid #222;border-radius:8px;padding:8px;text-align:center"><div style="font-size:14px;font-weight:700;color:#1E8449">'+F(s.total_approved)+' QR</div><div style="font-size:10px;color:#888">معتمد</div></div><div style="background:#111;border:1px solid #222;border-radius:8px;padding:8px;text-align:center"><div style="font-size:20px;font-weight:700;color:'+(s.progress_pct>=80?'#1E8449':s.progress_pct>=50?'#C8922A':'#C0392B')+'">'+s.progress_pct+'%</div><div style="font-size:10px;color:#888">%</div></div>';const items=r.data||[];const w=document.getElementById('boq-t');if(!items.length){w.innerHTML='<p style="text-align:center;color:#666;padding:20px">لا بنود</p>';return}let h='<table style="width:100%;border-collapse:collapse;font-size:11px"><thead><tr style="background:#0D1B3E;color:#C8922A"><th style="padding:5px">رقم</th><th style="padding:5px">وصف</th><th style="padding:5px">وحدة</th><th style="padding:5px">تعاقدي</th><th style="padding:5px">سعر</th><th style="padding:5px">منفذ</th><th style="padding:5px">معتمد</th><th style="padding:5px">%</th><th style="padding:5px">⚙</th></tr></thead><tbody>';items.forEach((it,i)=>{const p=Number(it.contracted_qty)>0?Math.round(Number(it.approved_qty||0)/Number(it.contracted_qty)*100):0;h+='<tr style="background:'+(i%2?'#111':'#0a0a0a')+'"><td style="padding:4px">'+it.item_number+'</td><td style="padding:4px">'+it.description+'</td><td style="padding:4px;text-align:center">'+it.unit+'</td><td style="padding:4px;text-align:center">'+F(it.contracted_qty)+'</td><td style="padding:4px;text-align:center">'+F(it.unit_rate)+'</td><td style="padding:4px;text-align:center;color:#7FB3D3;cursor:pointer" onclick="QS_Phase9._uq(\''+it.id+'\',\'executed\')">'+F(it.executed_qty)+'</td><td style="padding:4px;text-align:center;color:#1E8449;cursor:pointer" onclick="QS_Phase9._uq(\''+it.id+'\',\'approved\')">'+F(it.approved_qty)+'</td><td style="padding:4px;text-align:center;font-weight:700;color:'+(p>=80?'#1E8449':p>=50?'#C8922A':'#C0392B')+'">'+p+'%</td><td style="padding:4px"><button onclick="QS_Phase9._del(\''+it.id+\')" style="background:none;border:none;cursor:pointer;font-size:12px">x</button></td></tr>'});h+='</tbody></table>';w.innerHTML=h}catch(e){document.getElementById('boq-t').innerHTML='<p style="color:#C0392B">'+e.message+'</p>'}}

async function initIPCTab(c){c.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 style="color:#C8922A;margin:0">IPC</h3><button onclick="QS_Phase9._nipc()" style="padding:8px 12px;background:#C8922A;color:#fff;border:none;border-radius:6px;cursor:pointer;font-weight:700;font-size:12px">+ شهادة</button></div><div id="ipc-s" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:6px;margin-bottom:10px"></div><div id="ipc-l"></div>';await _li()}
async function _li(){try{const r=await A('payment-certificates','GET',null,{project_id:P()});const s=r.summary||{};document.getElementById('ipc-s').innerHTML='<div style="background:#111;border:1px solid #222;border-radius:8px;padding:8px;text-align:center"><div style="font-size:20px;font-weight:700;color:#C8922A">'+s.count+'</div><div style="font-size:10px;color:#888">شهادات</div></div><div style="background:#111;border:1px solid #222;border-radius:8px;padding:8px;text-align:center"><div style="font-size:14px;font-weight:700;color:#1E8449">'+F(s.total_net)+' QR</div><div style="font-size:10px;color:#888">صافي</div></div><div style="background:#111;border:1px solid #222;border-radius:8px;padding:8px;text-align:center"><div style="font-size:14px;font-weight:700;color:#C0392B">'+F(s.total_retention)+' QR</div><div style="font-size:10px;color:#888">محتجز</div></div>';const ipcs=r.data||[];const el=document.getElementById('ipc-l');if(!ipcs.length){el.innerHTML='<p style="text-align:center;color:#666;padding:20px">لا شهادات</p>';return}const sm={draft:'مسودة',submitted:'مقدمة',approved:'معتمدة',paid:'مدفوعة'};el.innerHTML=ipcs.map(i=>'<div style="background:#111;border:1px solid #222;border-radius:8px;padding:10px;margin-bottom:6px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:6px"><div><b style="color:#C8922A">IPC-'+i.ipc_number+'</b><br><span style="font-size:11px;color:#888">'+i.period_from+' → '+i.period_to+'</span></div><div style="text-align:center"><b style="color:#1E8449">'+F(i.this_certificate||i.net_amount)+' QR</b></div><div style="font-size:12px">'+(sm[i.status]||i.status)+'</div><button onclick="QS_Phase9._uipc(\''+i.id+'\',\''+i.status+\')" style="background:none;border:none;cursor:pointer;color:#7FB3D3;font-size:11px">تحديث</button></div>').join('')}catch(e){document.getElementById('ipc-l').innerHTML='<p style="color:#C0392B">'+e.message+'</p>'}}

async function initSCurveTab(c){c.innerHTML='<h3 style="color:#C8922A;margin-bottom:10px">S-Curve</h3><canvas id="sc-ch" style="width:100%;max-height:350px;background:#111;border-radius:8px"></canvas>';try{if(!window.Chart){const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js';document.head.appendChild(s);await new Promise(r=>{s.onload=r;setTimeout(r,3000)})}const r=await A('stats','GET',null,{project_id:P()});if(!r.stats?.scurve?.length){c.innerHTML+='<p style="text-align:center;color:#666;padding:15px">أنشئ IPCs أولا</p>';return}const sc=r.stats.scurve,cv=document.getElementById('sc-ch');if(_ch)_ch.destroy();_ch=new Chart(cv,{type:'line',data:{labels:sc.map(s=>'IPC-'+s.ipc),datasets:[{label:'مخطط',data:sc.map((_,i)=>Math.round((i+1)/sc.length*100)),borderColor:'#3498DB',borderWidth:2,borderDash:[5,5],fill:false,tension:.3},{label:'فعلي',data:sc.map(s=>s.cumulative_pct),borderColor:'#1E8449',backgroundColor:'rgba(30,132,73,0.15)',borderWidth:3,fill:true,tension:.3,pointRadius:5}]},options:{responsive:true,plugins:{legend:{labels:{color:'#aaa'}}},scales:{x:{ticks:{color:'#888'},grid:{color:'#222'}},y:{min:0,max:100,ticks:{color:'#888',callback:v=>v+'%'},grid:{color:'#222'}}}}})}catch(e){c.innerHTML+='<p style="color:#C0392B">'+e.message+'</p>'}}

async function initDashboardStats(c){c.innerHTML='<p style="color:#888;text-align:center">⏳</p>';try{const r=await A('stats','GET');const o=r.overview||{},a=r.alerts||{};c.innerHTML='<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:6px;margin-bottom:10px"><div style="background:#0D1B3E;border:2px solid #C8922A;border-radius:10px;padding:10px;text-align:center"><div style="font-size:24px;font-weight:700;color:#C8922A">'+(o.total_projects||0)+'</div><div style="font-size:10px;color:#aaa">مشاريع</div></div><div style="background:#0a1f0a;border:2px solid #1E8449;border-radius:10px;padding:10px;text-align:center"><div style="font-size:24px;font-weight:700;color:#1E8449">'+(o.active||0)+'</div><div style="font-size:10px;color:#aaa">نشط</div></div><div style="background:#111;border:2px solid #1A5276;border-radius:10px;padding:10px;text-align:center"><div style="font-size:14px;font-weight:700;color:#7FB3D3">'+F(o.total_contract_value)+' QR</div><div style="font-size:10px;color:#aaa">إجمالي</div></div></div>'+(a.critical_ncr||a.open_ncr||a.pending_ir?'<div style="background:#1f0a0a;border:1px solid #C0392B;border-radius:8px;padding:8px;margin-bottom:8px;font-size:12px"><b style="color:#C0392B">⚠️</b> '+(a.critical_ncr?a.critical_ncr+' NCR حرجة ':'')+( a.open_ncr?a.open_ncr+' NCR مفتوحة ':'')+(a.pending_ir?a.pending_ir+' IR معلق ':'')+'</div>':'')}catch(e){c.innerHTML='<p style="color:#C0392B">'+e.message+'</p>'}}

window.QS_Phase9={initBOQTab,initIPCTab,initSCurveTab,initDashboardStats,loadBOQData:_lb,loadIPCData:_li,
_add(){const v=prompt('رقم,وصف,وحدة,كمية,سعر:');if(!v)return;const[n,d,u,q,r]=v.split(',').map(s=>s.trim());A('boq','POST',{project_id:P(),item_number:n,description:d,unit:u,contracted_qty:q,unit_rate:r}).then(_lb).catch(e=>alert(e.message))},
_csv(){const v=prompt('CSV (رقم,وصف,وحدة,كمية,سعر):');if(!v)return;const items=v.split('\n').filter(l=>l.trim()).map(l=>{const[a,b,c,d,e]=l.split(',').map(s=>s.trim());return{item_number:a,description:b,unit:c,contracted_qty:d,unit_rate:e}});A('boq','POST',{project_id:P(),items}).then(_lb).catch(e=>alert(e.message))},
_uq(id,f){const v=prompt(f==='executed'?'منفذ:':'معتمد:');if(v===null)return;const b={};b[f+'_qty']=Number(v);A('boq','PUT',b,{id}).then(_lb).catch(e=>alert(e.message))},
_del(id){if(!confirm('حذف؟'))return;A('boq','DELETE',null,{id}).then(_lb).catch(e=>alert(e.message))},
_nipc(){const f=prompt('من:',new Date().toISOString().slice(0,8)+'01');if(!f)return;const t=prompt('إلى:',new Date().toISOString().slice(0,10));if(!t)return;A('payment-certificates','POST',{project_id:P(),period_from:f,period_to:t}).then(_li).catch(e=>alert(e.message))},
_uipc(id,st){const fl={draft:'submitted',submitted:'approved',approved:'paid'};const n=fl[st];if(!n)return alert('مدفوعة');if(!confirm(n+'?'))return;A('payment-certificates','PUT',{status:n},{id}).then(_li).catch(e=>alert(e.message))}
};})();