name: Deploy to Vercel
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: team_BUn6M6L492W1COsvFHruMx4X
  VERCEL_PROJECT_ID: prj_FbGrivFCdfJvoFycGRMd1U0ECq5D

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel Production
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
