name: k6 Load & Rate Limit Tests

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  k6-rate-limit-test:
    name: Rate Limit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run k6 Rate Limit Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/test-rate-limit.js

  k6-load-test:
    name: Load Test
    runs-on: ubuntu-latest
    needs: k6-rate-limit-test
    steps:
      - uses: actions/checkout@v4

      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/test-load.js

  k6-endpoints-test:
    name: All Endpoints Test
    runs-on: ubuntu-latest
    needs: k6-load-test
    steps:
      - uses: actions/checkout@v4

      - name: Run k6 Endpoints Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/test-all-endpoints.js
